#pragma once
// Auto-generated by SchemaClassGenerator - Do not manually edit!
#include <string>
#include <vector>

namespace Json { class Value; }

namespace SchemaClasses
{
	using namespace std;
	class CarInternal;
	class CarInternal;

	class Car
	{
	public:
		void Deserialize(Json::Value& jsonObj);
		void Serialize(Json::Value& jsonObj);
		void Destroy();

		string Make;
		string Model;
		int Year;
		CarInternal* Internal = nullptr;
		vector<CarInternal*> CarInternals;
	};
};
