#pragma once
// Auto-generated by SchemaClassGenerator - Do not manually edit!
#include <string>
#include <vector>

namespace Json { class Value; }

namespace SchemaClasses
{
	using namespace std;
	enum class SomeEnum;

	class CarInternal
	{
	public:
		void Deserialize(Json::Value& jsonObj);
		void Serialize(Json::Value& jsonObj);
		void Destroy();

		string StringField;
		int IntField;
		long LongField;
		float FloatField;
		double DoubleField;
		SomeEnum EnumField;
		vector<string> ArrayField;
	};
};
