#pragma once
// Auto-generated by SchemaClassGenerator - Do not manually edit!
#include <string>
#include <vector>

namespace SchemaClasses
{
	using namespace std;

	enum class SomeEnum
	{
		Enum1,
		Enum2,
		Enum3,
	};
	string SomeEnumToString(SomeEnum value);
	SomeEnum SomeEnumFromString(string value);
	vector<string> SomeEnumValues();
};
