#pragma once
// Auto-generated by DataSourceGenerator - Do not manually edit!
#include <string>
#include <vector>

namespace Json { class Value; }
namespace SchemaClasses { class Car; }

namespace DataSources
{
	using namespace std;

	class Test
	{
	private:
		Test(){}
	public:
		static const string FilePath;
		void Deserialize(Json::Value& jsonObj);
		void Serialize(Json::Value& jsonObj);
		void Destroy();
		vector<SchemaClasses::Car*> Root;
	};
};
