// Auto-generated by DataSourceGenerator - Do not manually edit!
#include "Test.gen.h"
#include "Car.gen.h"

#include <json/json.h>

using namespace SchemaClasses;
using namespace DataSources;
using namespace std;

/*static*/ const string Test::FilePath = "data\\test.json";

void Test::Deserialize(Json::Value& jsonObj)
{
	{
		auto& arr = jsonObj["Root"];
		Root.clear();
		Root.reserve(arr.size());
		for(auto& elem : arr)
		{
			auto val = new Car();
			val->Deserialize(elem);
			Root.push_back(val);
		};
	};
};

void Test::Serialize(Json::Value& jsonObj)
{
	{
		auto arr = Json::Value(Json::arrayValue);
		for(auto& elem : Root)
		{
			auto obj = Json::Value(Json::objectValue);
			elem->Serialize(obj);
			arr.append(obj);
		};
		jsonObj["Root"] = arr;
	};
};
